# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\x12\tfileshare\"!\n\rSearchRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"4\n\x0eSearchResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x13\n\x0bpeerAddress\x18\x02 \x01(\t\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"#\n\x10\x44ownloadResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\x11\n\x0f\x44iscoverRequest\"!\n\x10\x44iscoverResponse\x12\r\n\x05peers\x18\x01 \x03(\t2\xe9\x01\n\x0b\x46ileService\x12\x43\n\nSearchFile\x12\x18.fileshare.SearchRequest\x1a\x19.fileshare.SearchResponse\"\x00\x12I\n\x0c\x44ownloadFile\x12\x1a.fileshare.DownloadRequest\x1a\x1b.fileshare.DownloadResponse\"\x00\x12J\n\rDiscoverPeers\x12\x1a.fileshare.DiscoverRequest\x1a\x1b.fileshare.DiscoverResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEARCHREQUEST']._serialized_start=33
  _globals['_SEARCHREQUEST']._serialized_end=66
  _globals['_SEARCHRESPONSE']._serialized_start=68
  _globals['_SEARCHRESPONSE']._serialized_end=120
  _globals['_DOWNLOADREQUEST']._serialized_start=122
  _globals['_DOWNLOADREQUEST']._serialized_end=157
  _globals['_DOWNLOADRESPONSE']._serialized_start=159
  _globals['_DOWNLOADRESPONSE']._serialized_end=194
  _globals['_DISCOVERREQUEST']._serialized_start=196
  _globals['_DISCOVERREQUEST']._serialized_end=213
  _globals['_DISCOVERRESPONSE']._serialized_start=215
  _globals['_DISCOVERRESPONSE']._serialized_end=248
  _globals['_FILESERVICE']._serialized_start=251
  _globals['_FILESERVICE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
